import deepseek, dimensionX, flux
import time
import torch

def Text2180video(init_msg):
    start_time = time.time()
    index = 1

    # DeepSeek
    _deepseek = deepseek.DeepSeek()
    prompt = _deepseek.gen_prompt(init_msg)
    with open("outputs/text2180video/1.txt", "w") as f:
        f.write(f"initial message:\n\t{init_msg}\n\n")
        f.write(f"prompt generated by DeepSeek:\n\t{prompt}\n")

    # FLUX
    _flux = flux.Flux()
    image = _flux.gen_image(prompt)
    image.save("outputs/text2180video/1.png")

    # DimensionX
    _dimensionX = dimensionX.DimensonX()
    _dimensionX.img2video(
        prompt=prompt, 
        image=image, 
        output_video_path="outputs/text2180video/1.mp4", 
        scale=True, 
        interpolate=True
    )
    end_time = time.time()
    elapsed_time = end_time - start_time
    max_memory_allocated = torch.cuda.max_memory_allocated() / (1024**2)  # in MB
    return elapsed_time, max_memory_allocated

init_msg = "複式單位，可以坐在黑色沙發上看電視。"

elapsed_time, max_memory_allocated = Text2180video(init_msg)
print("done")
print(f"Elapsed time: {elapsed_time:.2f} seconds")
print(f"Peak GPU memory usage: {max_memory_allocated:.2f} MB")